import Foundation

/// Return the cached LLM summary for a single file. Reads from the
/// codemap; does not trigger a new summary generation pass (that runs once
/// at session start in `AppModel.refreshCodemapIfNeeded`).
struct AgentSummaryTool: AgentTool {
  static let toolName = "summary"

  struct Arguments: Decodable {
    let path: String

    enum CodingKeys: String, CodingKey {
      case path
      case filePath
      case filePathSnake = "file_path"
      case file
      case relativePath
      case relativePathSnake = "relative_path"
    }

    init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      path = try FlexibleModelDecoder.decodeRequiredString(
        from: container,
        preferredKey: .path,
        aliases: [.filePath, .filePathSnake, .file, .relativePath, .relativePathSnake],
        fieldName: "path"
      )
    }
  }

  let spec: AgentToolSpec

  init() {
    let schema = AgentToolParametersSchema(literal: [
      "type": "object",
      "additionalProperties": false,
      "required": ["path"],
      "properties": [
        "path": [
          "type": "string",
          "description":
            "Repo-relative path. Must match a path that the codemap indexer has seen.",
        ]
      ],
    ])
    spec = AgentToolSpec(
      name: Self.toolName,
      description:
        "Return the cached one-paragraph summary of a file, generated by the codemap pass at session start. Returns an explicit 'no summary yet' message if the entry exists but the summary pass hasn't covered it.",
      parameters: schema
    )
  }

  func invoke(arguments: Data, context: AgentToolContext) async throws -> AgentToolInvocationResult
  {
    let args: Arguments
    do {
      args = try JSONDecoder().decode(Arguments.self, from: arguments)
    } catch {
      return .failure(.invalidArguments(agentToolDecodingErrorDescription(error)))
    }
    let normalized = AgentCodemapPath.normalize(
      args.path, workingDirectory: context.workingDirectory)
    let store = context.codemapStore()
    guard let entry = store.loadEntry(forRelativePath: normalized) else {
      return .failure(
        "No codemap entry for '\(normalized)'. Use `list_files` to see what's been indexed."
      )
    }
    guard let summary = entry.summary, !summary.isEmpty else {
      if let docBlurb = entry.docBlurb, !docBlurb.isEmpty {
        return .ok("[\(entry.relativePath) · docs]\n\n\(docBlurb)")
      }
      return .ok(
        "No summary yet for '\(entry.relativePath)'. Summary generation runs once per session; this file may have been added or changed after the pass."
      )
    }
    if let model = entry.summaryModel {
      return .ok("[\(entry.relativePath) · summarized by \(model)]\n\n\(summary)")
    }
    return .ok("[\(entry.relativePath)]\n\n\(summary)")
  }
}
