import Foundation

/// Return the cached LLM summary for a single file. Reads from the
/// codemap; does not trigger a new summary generation pass (that runs once
/// at session start in `AppModel.refreshCodemapIfNeeded`).
struct AgentSummaryTool: AgentTool {
  static let toolName = "summary"

  struct Arguments: Codable {
    let path: String
  }

  let spec: AgentToolSpec

  init() {
    let schema = AgentToolParametersSchema(literal:[
      "type": "object",
      "additionalProperties": false,
      "required": ["path"],
      "properties": [
        "path": [
          "type": "string",
          "description":
            "Repo-relative path. Must match a path that the codemap indexer has seen.",
        ]
      ],
    ])
    spec = AgentToolSpec(
      name: Self.toolName,
      description:
        "Return the cached one-paragraph summary of a file, generated by the codemap pass at session start. Returns an explicit 'no summary yet' message if the entry exists but the summary pass hasn't covered it.",
      parameters: schema
    )
  }

  func invoke(arguments: Data, context: AgentToolContext) async throws -> AgentToolInvocationResult
  {
    let args: Arguments
    do {
      args = try JSONDecoder().decode(Arguments.self, from: arguments)
    } catch {
      return .failure(.invalidArguments(error.localizedDescription))
    }
    let normalized = AgentCodemapPath.normalize(
      args.path, workingDirectory: context.workingDirectory)
    let store = context.codemapStore()
    guard let entry = store.loadEntry(forRelativePath: normalized) else {
      return .failure(
        "No codemap entry for '\(normalized)'. Use `list_files` to see what's been indexed."
      )
    }
    guard let summary = entry.summary, !summary.isEmpty else {
      return .ok(
        "No summary yet for '\(entry.relativePath)'. Summary generation runs once per session; this file may have been added or changed after the pass."
      )
    }
    if let model = entry.summaryModel {
      return .ok("[\(entry.relativePath) · summarized by \(model)]\n\n\(summary)")
    }
    return .ok("[\(entry.relativePath)]\n\n\(summary)")
  }
}
