import Foundation
import FoundationModels
import Testing

@testable import Compass

/// Compile-only test exercising the `commits` parameter added to
/// ``ArchitectureGraph/explain(graph:repoURL:commits:)`.
///
/// ## What this test covers
///
/// `ArchitectureGraph.explain(graph:repoURL:commits:)` now accepts a
/// `commits: [SessionCommit]` parameter so the model prompt can say
/// "this file was generated by commit X" when commit context is
/// available. This test confirms the new parameter label is valid and
/// compiles correctly at every call site in the chain.
///
/// ## How it works
///
/// This test uses the same shadow-pattern approach established in
/// ``ExploreFileExplainerGuardPathTests``: it exercises the new
/// call signature by calling `ArchitectureGraph.explain` with a
/// valid `ImportGraph` and `[SessionCommit]` value. Compile success
/// is the only goal — no runtime assertions are made. If the test
/// compiles, the parameter labels are correct throughout the chain.
///
/// No runtime behavior is expected or meaningful here.
struct ExploreArchitectureGraphExplainCommitsParamTests {

  /// Confirms that `ArchitectureGraph.explain(graph:repoURL:commits:)`
  /// compiles with a bare `ImportGraph` and an empty `[SessionCommit]`
  /// array. This exercises the new `commits` parameter label in the
  /// `ArchitectureGraph` enum's static method signature.
  @Test
  func explain_withCommitsParameter_compiles() {
    // Build a minimal ImportGraph with a single node and no edges.
    var graph = ImportGraph()
    graph.addNode(ImportGraph.Node(path: "Sources/App.swift"))
    // graph.edges is empty — this is fine for the call.

    // An empty commits array is valid input; it simply means no
    // generation context is available. The method handles this gracefully.
    let commits: [SessionCommit] = []

    // This line is the entire point of the test: confirming that the
    // three-parameter call signature compiles without errors.
    //
    // NOTE: This is marked @Test so the Swift compiler processes it.
    // The async call itself is not awaited because we only care about
    // compile-time resolution, not runtime output.
    Task {
      _ = await ArchitectureGraph.explain(
        graph: graph,
        repoURL: URL(fileURLWithPath: "/tmp/test"),
        commits: commits
      )
    }
  }
}