import SwiftUI
import Testing

@testable import Compass

struct ExploreExplanationSheetTests {

  // MARK: - explanation branch (line 1675)

  @Test
  func explanationProvided_showsExplanationText() throws {
    let sheet = ExplanationSheet(
      fileName: "Gen.swift",
      explanation: "Generated by the plan executor.",
      reason: nil
    )
    let body = String(reflecting: sheet.body)
    #expect(body.contains("Generated by the plan executor."))
  }

  // MARK: - reason branch (line 1680)

  @Test
  func reasonProvided_noExplanation_showsReasonMessage() throws {
    let sheet = ExplanationSheet(
      fileName: "Gen.swift",
      explanation: nil,
      reason: .foundationModelsUnavailable
    )
    let body = String(reflecting: sheet.body)
    #expect(body.contains("Explanation Unavailable"))
    #expect(body.contains(ExplainUnavailableReason.foundationModelsUnavailable.message))
  }

  // MARK: - else branch (line 1690)

  @Test
  func neitherExplanationNorReason_showsUnavailableText() throws {
    let sheet = ExplanationSheet(
      fileName: "Gen.swift",
      explanation: nil,
      reason: nil
    )
    let body = String(reflecting: sheet.body)
    #expect(body.contains("Explanation unavailable."))
  }
}
