import Foundation

/// # Explore Layer
///
/// `RepoQnA` provides repository-scale Q&A for the Explore layer.
/// It answers natural-language questions about the codebase, grounded in the actual
/// diff and codemap of a commit range, so answers reflect reality rather than
/// hallucinated context.
///
/// ## Role in the Explore layer
///
/// ``RepoQnA`` is available independently for free-form questions about the repository,
/// distinct from ``CommitExplainer`` (per-file, per-commit summaries), ``CommitTourGenerator``
/// (multi-commit guided tours), and ``ArchitectureGraph`` (static import-graph analysis).
/// All three are called through or alongside ``FileExplainer``; ``RepoQnA`` stands alone
/// as the exploratory Q&A surface.
///
/// ## Generated narration boundary
///
/// All public methods are gated ``@available(macOS 26.0, *)`` and stream through
/// the generated narration shim. All return `nil` when narration is unavailable or
/// produces no content.

/// Interactive Q&A about repository changes, grounded in the actual diff
/// and codemap of a commit range.
///
/// ## Three-step pipeline
///
/// 1. ``FileExplainer/changes(for:commits:)`` — retrieves the file list with
///    line-count stats and codemap summaries (if the file has been indexed).
///    Receives commits newest-first; internally reversed for chronological
///    git operations.
///
/// 2. Raw `git diff` over the commit range — ``git diff sha^..sha`` for a single
///    commit, ``git diff newest..oldest`` for a range. Truncated to ~8000 chars
///    to stay within token limits while preserving early file headers.
///
/// 3. Generated narration — the file list and truncated diff
///    are streamed as a single prompt to produce a grounded plain-English answer.
///
/// ## `isAvailable` guard contract
///
/// All public methods return `nil` when `FoundationModelsAvailability.isAvailable`
/// is `false`. Callers must check the return value and handle the `nil` case
/// gracefully (typically by showing a fallback message).
///
/// ## Availability
///
/// Available only on macOS 26.0 and later.
@available(macOS 26.0, *)
public enum RepoQnA {
  /// A Q&A answer with its supporting source files.
  public struct Answer {
    /// The plain-English answer generated by the model.
    public let text: String
    /// Relative paths of the files the answer was grounded in.
    public let sources: [String]
  }

  /// Answers a natural-language question about a commit range using
  /// generated narration, grounded in the actual diff and codemap context.
  ///
  /// The answer is assembled by first collecting file changes with codemap
  /// summaries, then building a combined prompt from the file list and the
  /// truncated diff text, and finally streaming the result from Foundation
  /// narration. The diff is truncated to approximately 8 000 characters before
  /// being sent to the model to respect token limits.
  ///
  /// Returns `nil` when generated narration is unavailable, when no commits are
  /// supplied, or when the model produces no content.
  public static func answer(
    question: String,
    repoURL: URL,
    commits: [SessionCommit]
  ) async -> Answer? {
    guard FoundationModelsAvailability.isAvailable else { return nil }

    // 1. Get file changes with codemap summaries.
    let changes = await FileExplainer.changes(for: repoURL, commits: commits)

    // 2. Get the actual diff text over the commit range.
    guard let diff = await CommitExplainer.commitDiffRange(commits: commits, repoURL: repoURL)
    else {
      return nil
    }

    // 3. Build the file-listing section for the prompt.
    var fileSection = "Changed files:\n"
    for change in changes {
      var line = "  \(change.relativePath)  \(change.lineCountLabel)"
      if let summary = change.summary {
        line += " — \(summary)"
      }
      fileSection += line + "\n"
    }

    // 4. Truncate the diff to avoid token limits (~8000 chars for the diff portion).
    // We keep the FIRST maxDiffChars characters so rename headers and early file
    // additions remain visible to the model — dropping the start would lose context.
    let truncatedDiff: String
    let maxDiffChars = 8000
    if diff.count > maxDiffChars {
      truncatedDiff = String(diff.prefix(maxDiffChars)) + "\n[... diff truncated ...]"
    } else {
      // diff is a non-optional String here: the `guard let diff =` on line 86 already
      // unwrapped the optional, so `diff` is String throughout this else branch.
      truncatedDiff = diff
    }

    let prompt = """
      You are a helpful software engineer answering a question about a git diff.
      Use the file list and diff below as your source of truth. If the diff
      does not contain enough information to answer, say so clearly.

      Question: \(question)

      \(fileSection)
      Diff:
      \(truncatedDiff)
      """

    // 5. Stream the answer from generated narration.
    guard let result = await FoundationModelsAvailability._streamText(prompt: prompt) else {
      return nil
    }
    let sources = changes.map(\.relativePath)
    return Answer(text: result, sources: sources)
  }
}
