import Foundation

#if canImport(FoundationModels)
  import FoundationModels
#endif

/// Interactive Q&A about repository changes, grounded in the actual diff
/// and codemap of a commit range.
///
/// ## Three-step pipeline
///
/// 1. ``FileExplainer/changes(for:commits:)`` — retrieves the file list with
///    line-count stats and codemap summaries (if the file has been indexed).
///    Receives commits newest-first; internally reversed for chronological
///    git operations.
///
/// 2. Raw `git diff` over the commit range — ``git diff sha^..sha`` for a single
///    commit, ``git diff newest..oldest`` for a range. Truncated to ~8000 chars
///    to stay within token limits while preserving early file headers.
///
/// 3. Foundation Models text generation — the file list and truncated diff
///    are streamed as a single prompt to produce a grounded plain-English answer.
///
/// ## `isAvailable` guard contract
///
/// All public methods return `nil` when `FoundationModelsAvailability.isAvailable`
/// is `false`. Callers must check the return value and handle the `nil` case
/// gracefully (typically by showing a fallback message).
///
/// ## Availability
///
/// Available only on macOS 26.0 and later.
@available(macOS 26.0, *)
enum RepoQnA {
  /// A Q&A answer with its supporting source files.
  struct Answer {
    /// The plain-English answer generated by the model.
    let text: String
    /// Relative paths of the files the answer was grounded in.
    let sources: [String]
  }

  /// Answers a natural-language question about a commit range using
  /// Foundation Models, grounded in the actual diff and codemap context.
  ///
  /// The answer is assembled by first collecting file changes with codemap
  /// summaries, then building a combined prompt from the file list and the
  /// truncated diff text, and finally streaming the result from Foundation
  /// Models. The diff is truncated to approximately 8 000 characters before
  /// being sent to the model to respect token limits.
  ///
  /// Returns `nil` when Foundation Models is unavailable, when no commits are
  /// supplied, or when the model produces no content.
  static func answer(
    question: String,
    repoURL: URL,
    commits: [SessionCommit]
  ) async -> Answer? {
    guard FoundationModelsAvailability.isAvailable else { return nil }
    guard let first = commits.first else { return nil }

    // 1. Get file changes with codemap summaries.
    let changes = await FileExplainer.changes(for: repoURL, commits: commits)

    // 2. Get the actual diff text over the commit range.
    let diff: String
    if commits.count == 1 {
      diff = await CommitExplainer.gitDiff(sha: first.sha, repoURL: repoURL)
    } else if let last = commits.last {
      diff = await CommitExplainer.gitDiffRange(newest: first.sha, oldest: last.sha, repoURL: repoURL)
    } else {
      return nil
    }

    // 3. Build the file-listing section for the prompt.
    var fileSection = "Changed files:\n"
    for change in changes {
      var line = "  \(change.relativePath)  \(change.lineCountLabel)"
      if let summary = change.summary {
        line += " — \(summary)"
      }
      fileSection += line + "\n"
    }

    // 4. Truncate the diff to avoid token limits (~8000 chars for the diff portion).
    // We keep the FIRST maxDiffChars characters so rename headers and early file
    // additions remain visible to the model — dropping the start would lose context.
    let truncatedDiff: String
    let maxDiffChars = 8000
    if diff.count > maxDiffChars {
      truncatedDiff = String(diff.prefix(maxDiffChars)) + "\n[... diff truncated ...]"
    } else {
      truncatedDiff = diff
    }

    let prompt = """
      You are a helpful software engineer answering a question about a git diff.
      Use the file list and diff below as your source of truth. If the diff
      does not contain enough information to answer, say so clearly.

      Question: \(question)

      \(fileSection)
      Diff:
      \(truncatedDiff)
      """

    // 5. Stream the answer from Foundation Models.
    guard let result = await FoundationModelsAvailability._streamText(prompt: prompt) else {
      return nil
    }
    let sources = changes.map(\.relativePath)
    return Answer(text: result, sources: sources)
  }
}