import Foundation
import FoundationModels

/// Interactive Q&A about repository changes, grounded in the actual diff
/// and codemap of a commit range.
/// Available only on macOS 26.0 and later.
@available(macOS 26.0, *)
enum RepoQnA {
  /// A Q&A answer with its supporting source files.
  struct Answer {
    /// The plain-English answer generated by the model.
    let text: String
    /// Relative paths of the files the answer was grounded in.
    let sources: [String]
  }

  /// Answers a natural-language question about a commit range using the
  /// actual diff and codemap summaries as grounding context.
  ///
  /// - Parameters:
  ///   - question: The user's question about the changes.
  ///   - repoURL: The working-copy root of the repository.
  ///   - commits: The commits to analyse. Single-commit uses `sha^..sha`;
  ///     multi-commit uses `from..to` (oldest → newest).
  /// - Returns: An `Answer` with the generated text and supporting source
  ///   files, or `nil` if Foundation Models is unavailable or produces no
  ///   content.
  static func answer(
    question: String,
    repoURL: URL,
    commits: [SessionCommit]
  ) async -> Answer? {
    guard FoundationModelsAvailability.isAvailable else { return nil }
    guard let first = commits.first else { return nil }

    // 1. Get file changes with codemap summaries.
    let changes = await FileExplainer.changes(for: repoURL, commits: commits)

    // 2. Get the actual diff text over the commit range.
    let diff: String
    if commits.count == 1 {
      let result = try? await ProcessRunner.runEnv(
        "git", ["diff", "\(first.sha)^..\(first.sha)"],
        workingDirectory: repoURL
      )
      diff = result?.stdout ?? ""
    } else if let last = commits.last {
      let result = try? await ProcessRunner.runEnv(
        "git", ["diff", "\(first.sha)..\(last.sha)"],
        workingDirectory: repoURL
      )
      diff = result?.stdout ?? ""
    } else {
      return nil
    }

    // 3. Build the file-listing section for the prompt.
    var fileSection = "Changed files:\n"
    for change in changes {
      var line = "  \(change.relativePath)  \(change.lineCountLabel)"
      if let summary = change.summary {
        line += " — \(summary)"
      }
      fileSection += line + "\n"
    }

    // 4. Truncate the diff to avoid token limits (~8000 chars for the diff portion).
    let truncatedDiff: String
    let maxDiffChars = 8000
    if diff.count > maxDiffChars {
      truncatedDiff = String(diff.dropFirst(diff.count - maxDiffChars)) + "\n[... diff truncated ...]"
    } else {
      truncatedDiff = diff
    }

    let prompt = """
      You are a helpful software engineer answering a question about a git diff.
      Use the file list and diff below as your source of truth. If the diff
      does not contain enough information to answer, say so clearly.

      Question: \(question)

      \(fileSection)
      Diff:
      \(truncatedDiff)
      """

    // 5. Stream the answer from Foundation Models.
    do {
      let session = LanguageModelSession(model: .default)
      var fullText = ""
      for try await snapshot in session.streamResponse(to: prompt) {
        fullText += snapshot.content
      }
      let result = fullText.trimmingCharacters(in: .whitespacesAndNewlines)
      guard !result.isEmpty else { return nil }

      let sources = changes.map(\.relativePath)
      return Answer(text: result, sources: sources)
    } catch {
      return nil
    }
  }
}